import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, Text, View, useWindowDimensions } from 'react-native';
import { useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/src/api';
import { auth, onAuthStateChanged, signOut } from '@/src/firebase';
import type { GameNight } from '@/src/types';
import { colors, styles } from '@/src/styles';
import { LanguageSwitcher, useLanguage } from '@/src/i18n';

const dateLabel = (date: string, language: string) => new Intl.DateTimeFormat(language === 'tr' ? 'tr-TR' : 'en', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(date));
function Badge({ children, tone = 'green' }: { children: string; tone?: 'green' | 'gold' | 'red' }) { return <View style={{ backgroundColor: tone === 'green' ? colors.mint : tone === 'gold' ? '#f8ecd5' : '#f7dfdc', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5 }}><Text style={{ color: tone === 'green' ? colors.green : tone === 'gold' ? '#8b5a12' : colors.red, fontWeight: '800', fontSize: 11 }}>{children}</Text></View>; }
function NightCard({ night, onRefresh }: { night: GameNight; onRefresh: () => void }) {
	const { language, t } = useLanguage();
	const { width } = useWindowDimensions();
	const compact = width < 560;
	const [joined, setJoined] = useState(night.id === 'night-1');
	const mutation = useMutation<void>({ mutationFn: async () => { if (joined) await api.leave(night.id); else await api.join(night.id); }, onSuccess: () => { setJoined(!joined); onRefresh(); } });
	const full = night.participantCount >= night.capacity;
	return <View style={[styles.card, { marginBottom: 14, padding: compact ? 16 : 20 }]}><View style={styles.between}><View style={{ flex: 1, paddingRight: 12 }}><Text style={{ color: colors.ink, fontSize: 20, fontWeight: '800' }}>{night.title}</Text><Text style={[styles.subtitle, { marginTop: 5 }]}>{dateLabel(night.startsAt, language)}</Text></View><Badge tone={night.status === 'PUBLISHED' ? 'green' : 'gold'}>{night.status}</Badge></View><View style={{ marginTop: 18, gap: 8 }}><Text style={{ color: colors.ink, fontWeight: '700' }}>⌖ {night.venueName}</Text><Text style={{ color: colors.muted }}>♟ {t('night.players', { count: night.participantCount, capacity: night.capacity })} · {full ? t('night.full') : t('night.places', { count: night.capacity - night.participantCount })}</Text>{night.notes ? <Text style={{ color: colors.muted, lineHeight: 21 }}>{night.notes}</Text> : null}</View><View style={[styles.between, { marginTop: 18 }, compact && { flexDirection: 'column', alignItems: 'stretch', gap: 10 }]}><Pressable onPress={() => {}} style={compact ? { minHeight: 44, justifyContent: 'center' } : undefined}><Text style={{ color: colors.green, fontWeight: '800' }}>{t('night.details')}</Text></Pressable>{night.status === 'PUBLISHED' && <Pressable disabled={full && !joined || mutation.isPending} onPress={() => mutation.mutate()} style={[styles.button, joined && styles.secondaryButton, compact && { width: '100%' }]}><Text style={[styles.buttonText, joined && styles.secondaryText]}>{mutation.isPending ? t('common.working') : joined ? t('night.cancel') : full ? t('night.fullButton') : t('night.join')}</Text></Pressable>}</View></View>;
}
function Overview({ go, enabled }: { go: (tab: string) => void; enabled: boolean }) { const { t } = useLanguage(); const queryClient = useQueryClient(); const nights = useQuery({ queryKey: ['nights'], queryFn: () => api.nights(), enabled }); const player = useQuery({ queryKey: ['me'], queryFn: () => api.me(), enabled }); if (!enabled || nights.isLoading || player.isLoading) return <ActivityIndicator color={colors.green} size="large" />; if (nights.isError || player.isError) return <ErrorState error={nights.error ?? player.error} />; const p = player.data!; return <><View style={[styles.between, { marginBottom: 24 }]}><View><Text style={styles.eyebrow}>{t('home.greeting', { name: p.displayName.toUpperCase() })}</Text><Text style={[styles.title, { marginTop: 7 }]}>{t('home.title')}</Text></View><Pressable onPress={() => go('profile')} style={{ backgroundColor: colors.mint, width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' }}><Text style={{ color: colors.green, fontWeight: '900' }}>{p.displayName[0]}</Text></Pressable></View><View style={[styles.card, { backgroundColor: colors.green, marginBottom: 26 }]}><Text style={{ color: '#b9dfc5', fontWeight: '800' }}>{t('home.rank')}</Text><Text style={{ color: colors.white, fontSize: 28, fontWeight: '800', marginTop: 8 }}>{p.rank.currentRank.title}</Text><Text style={{ color: '#d4edda', marginTop: 6 }}>{p.rank.attendedGameCount} · {p.rank.gamesUntilNextRank ? t('home.until', { count: p.rank.gamesUntilNextRank, rank: p.rank.nextRank?.title ?? '' }) : t('home.topRank')}</Text><View style={{ height: 7, backgroundColor: '#477b62', borderRadius: 8, marginTop: 18 }}><View style={{ height: 7, width: `${Math.min(100, p.rank.attendedGameCount * 10)}%`, backgroundColor: colors.gold, borderRadius: 8 }} /></View></View><View style={[styles.between, { marginBottom: 13 }]}><Text style={{ color: colors.ink, fontSize: 21, fontWeight: '800' }}>{t('home.upcoming')}</Text><Pressable onPress={() => go('nights')}><Text style={{ color: colors.green, fontWeight: '800' }}>{t('common.seeAll')}</Text></Pressable></View>{nights.data!.filter((n) => n.status !== 'CANCELLED').slice(0, 2).map((night) => <NightCard key={night.id} night={night} onRefresh={() => queryClient.invalidateQueries({ queryKey: ['nights'] })} />)}</>; }
function ErrorState({ error }: { error: Error | null }) { const router = useRouter(); const { t } = useLanguage(); const unauthorized = error?.message === 'Authentication required'; return <View style={[styles.card, { marginTop: 20 }]}><Text style={{ color: colors.ink, fontSize: 18, fontWeight: '800' }}>{unauthorized ? t('error.expired') : t('error.load')}</Text><Text style={[styles.subtitle, { marginTop: 8 }]}>{unauthorized ? t('error.signIn') : error?.message ?? t('error.try')}</Text><Pressable onPress={() => unauthorized ? router.replace('/login') : undefined} style={[styles.button, { marginTop: 16 }]}><Text style={styles.buttonText}>{unauthorized ? t('error.login') : t('error.retry')}</Text></Pressable></View>; }
function Leaderboard() { const { t } = useLanguage(); const query = useQuery({ queryKey: ['leaderboard'], queryFn: () => api.leaderboard() }); if (query.isLoading) return <ActivityIndicator color={colors.green} />; if (query.isError) return <Text style={styles.subtitle}>{t('leaderboard.unavailable')}</Text>; return <><Text style={styles.eyebrow}>{t('home.community')}</Text><Text style={[styles.title, { marginTop: 7, marginBottom: 8 }]}>{t('nav.leaderboard')}</Text><Text style={[styles.subtitle, { marginBottom: 20 }]}>{t('leaderboard.subtitle')}</Text><View style={styles.card}>{query.data!.entries.map((entry, index) => <View key={entry.playerId} style={[styles.between, { paddingVertical: 13, borderBottomWidth: index === query.data!.entries.length - 1 ? 0 : 1, borderBottomColor: colors.line }]}><View style={styles.row}><Text style={{ width: 34, color: colors.gold, fontWeight: '900' }}>{String(index + 1).padStart(2, '0')}</Text><View><Text style={{ color: colors.ink, fontWeight: '800' }}>{entry.displayName}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 2 }}>{entry.rank.currentRank.title}</Text></View></View><Text style={{ color: colors.green, fontWeight: '900' }}>{entry.rank.attendedGameCount}</Text></View>)}</View></>; }
function Profile({ enabled }: { enabled: boolean }) { const { t } = useLanguage(); const query = useQuery({ queryKey: ['me'], queryFn: () => api.me(), enabled }); if (!enabled || query.isLoading) return <ActivityIndicator color={colors.green} />; if (query.isError) return <ErrorState error={query.error} />; const p = query.data!; return <><Text style={styles.eyebrow}>{t('profile.identity')}</Text><Text style={[styles.title, { marginTop: 7 }]}>{t('nav.profile')}</Text><View style={[styles.card, { marginTop: 22, alignItems: 'center' }]}><View style={{ backgroundColor: colors.mint, width: 74, height: 74, borderRadius: 37, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 30, color: colors.green, fontWeight: '900' }}>{p.displayName[0]}</Text></View><Text style={{ color: colors.ink, fontSize: 24, fontWeight: '800', marginTop: 14 }}>{p.displayName}</Text><Text style={styles.subtitle}>{p.email}</Text><Badge>{p.role}</Badge></View><View style={[styles.card, { marginTop: 14 }]}><Text style={{ color: colors.ink, fontWeight: '800', fontSize: 17 }}>{t('profile.progress')}</Text><Text style={[styles.subtitle, { marginTop: 10 }]}>{t('profile.attendedNights', { count: p.rank.attendedGameCount })}</Text><Text style={{ color: colors.green, fontWeight: '800', marginTop: 10 }}>{p.rank.currentRank.title} → {p.rank.nextRank?.title ?? t('profile.master')}</Text></View></>; }
export default function Home() {
	const { t } = useLanguage();
	const { width } = useWindowDimensions();
	const compact = width < 560;
	const [tab, setTab] = useState('home');
	const [authReady, setAuthReady] = useState(false);
	const [authenticated, setAuthenticated] = useState(false);
	const router = useRouter();
	useEffect(() => onAuthStateChanged(auth, (user) => { setAuthenticated(Boolean(user)); setAuthReady(true); if (!user && !process.env.EXPO_PUBLIC_DEMO_MODE) router.replace('/login'); }), [router]);
	const tabs = [['home', t('nav.home'), '⌂'], ['nights', t('nav.nights'), '♟'], ['leaderboard', t('nav.leaderboard'), '↗'], ['profile', t('nav.profile'), '○']];
	if (!authReady || (!authenticated && !process.env.EXPO_PUBLIC_DEMO_MODE)) return <SafeAreaView style={styles.page}><View style={[styles.shell, { flex: 1, justifyContent: 'center', alignItems: 'center' }]}><ActivityIndicator color={colors.green} size="large" /></View></SafeAreaView>;
	const enabled = authenticated || process.env.EXPO_PUBLIC_DEMO_MODE === 'true';
	const logout = async () => { await signOut(auth); router.replace('/login'); };
	return <SafeAreaView style={styles.page}><View style={[styles.shell, { paddingHorizontal: compact ? 16 : 28, paddingVertical: compact ? 16 : 24 }]}>
		<View style={[styles.between, { marginBottom: compact ? 16 : 22 }]}><Text style={{ color: colors.green, fontSize: compact ? 18 : 20, fontWeight: '900', letterSpacing: 1 }}>TROY / BOTC</Text><View style={[styles.row, { gap: compact ? 10 : 14 }]}><LanguageSwitcher /><Pressable onPress={logout} accessibilityRole="button" hitSlop={8}><Text style={{ color: colors.red, fontWeight: '800', fontSize: compact ? 12 : 14 }}>{compact ? '↪' : t('nav.logout')}</Text></Pressable></View></View>
		<ScrollView contentContainerStyle={{ paddingBottom: 100 }} keyboardShouldPersistTaps="handled">{tab === 'home' && <Overview go={setTab} enabled={enabled} />}{tab === 'nights' && <><Text style={styles.eyebrow}>{t('home.findTable')}</Text><Text style={[styles.title, { marginTop: 7, marginBottom: 20, fontSize: compact ? 30 : 34 }]}>{t('nav.nights')}</Text><NightsList /></>}{tab === 'leaderboard' && <Leaderboard />}{tab === 'profile' && <Profile enabled={enabled} />}</ScrollView>
		<View style={[styles.row, { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: compact ? 4 : 6, justifyContent: 'space-around' }]}>{tabs.map(([key, label, icon]) => <Pressable key={key} onPress={() => setTab(key)} accessibilityRole="tab" style={{ flex: 1, minHeight: 52, padding: compact ? 6 : 10, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: tab === key ? colors.green : colors.muted, fontSize: compact ? 18 : 12, fontWeight: '800' }}>{compact ? icon : label}</Text>{compact && <Text numberOfLines={1} adjustsFontSizeToFit style={{ color: tab === key ? colors.green : colors.muted, fontSize: 10, fontWeight: '800', marginTop: 2 }}>{label}</Text>}</Pressable>)}</View>
	</View></SafeAreaView>;
}
function NightsList() { const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['nights'], queryFn: () => api.nights() }); if (query.isLoading) return <ActivityIndicator color={colors.green} />; return <>{query.data!.map((night) => <NightCard key={night.id} night={night} onRefresh={() => queryClient.invalidateQueries({ queryKey: ['nights'] })} />)}</>; }
